<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:property name="robot_base_length" value="0.30" />
    <xacro:property name="robot_base_width" value="0.52" />
    <xacro:property name="robot_base_offset_length" value="0.45" />
    <xacro:property name="robot_base_offset_width" value="0.02" />
    <xacro:property name="robot_base_height" value="0.99" />
    <xacro:property name="robotcell_length" value="1.44" />
    <xacro:property name="robotcell_width" value="0.94" />
    <xacro:property name="robotcell_height" value="1.16" />
    <xacro:property name="shield_thickness" value="0.03" />

    <xacro:include filename="$(find realsense2_description)/urdf/_d435.urdf.xacro" />
    <xacro:arg name="use_nominal_extrinsics" default="false"/>
    <xacro:arg name="add_plug" default="false" />
    <xacro:arg name="use_mesh" default="true" />
    <xacro:sensor_d435 
        parent="robotcell_link" 
        use_nominal_extrinsics="$(arg use_nominal_extrinsics)" 
        add_plug="$(arg add_plug)" 
        use_mesh="$(arg use_mesh)">
        <origin xyz="0  0  ${robotcell_height+robot_base_height-shield_thickness}" rpy="${pi/2} ${pi/2} 0" />
    </xacro:sensor_d435>

</robot>

<!-- ${robotcell_length/2} ${robotcell_width/2}
${pi/2} ${pi/2} -->